<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>LealInfoPDV</AssemblyName>
    <RootNamespace>LealInfoPDV</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>10.283.0</Version>
    <AssemblyVersion>10.283.0.0</AssemblyVersion>
    <FileVersion>10.283.0.0</FileVersion>
    <ApplicationIcon>Assets\lealinfo.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup><Compile Remove="realtime\**\*.cs" /></ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.12" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3537.50" />
    <PackageReference Include="System.Speech" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\*.png"><CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory></Content>
    <Content Include="Assets\*.mp4"><CopyToOutputDirectory>Always</CopyToOutputDirectory><CopyToPublishDirectory>Always</CopyToPublishDirectory></Content>
  </ItemGroup>
</Project>