<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="../../LicenseManager.cs" Link="LicenseManager.cs" />
    <Compile Include="../LealInfoLicenseGenerator/LicenseSigner.cs" Link="LicenseSigner.cs" />
  </ItemGroup>
</Project>
